// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AddModuleCssNamespace {
  export interface IAddModuleCss {
    overlay: string;
    popup: string;
    skeletons: string;
    "template-link": string;
  }
}

declare const AddModuleCssModule: AddModuleCssNamespace.IAddModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AddModuleCssNamespace.IAddModuleCss;
};

export = AddModuleCssModule;
