// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModalModuleCssNamespace {
  export interface IModalModuleCss {
    close: string;
    heading: string;
    modal: string;
    overlay: string;
    title: string;
  }
}

declare const ModalModuleCssModule: ModalModuleCssNamespace.IModalModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ModalModuleCssNamespace.IModalModuleCss;
};

export = ModalModuleCssModule;
