// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RootModuleCssNamespace {
  export interface IRootModuleCss {
    active: string;
    content: string;
    heading: string;
    "nav-link": string;
    sidebar: string;
  }
}

declare const RootModuleCssModule: RootModuleCssNamespace.IRootModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: RootModuleCssNamespace.IRootModuleCss;
};

export = RootModuleCssModule;
