// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormModuleCssNamespace {
  export interface IFormModuleCss {
    counter: string;
    error: string;
    "error-float": string;
    hidden: string;
    input: string;
    required: string;
  }
}

declare const FormModuleCssModule: FormModuleCssNamespace.IFormModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormModuleCssNamespace.IFormModuleCss;
};

export = FormModuleCssModule;
