// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LogsAppModuleCssNamespace {
  export interface ILogsAppModuleCss {
    link: string;
    overlay: string;
    popup: string;
  }
}

declare const LogsAppModuleCssModule: LogsAppModuleCssNamespace.ILogsAppModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LogsAppModuleCssNamespace.ILogsAppModuleCss;
};

export = LogsAppModuleCssModule;
